services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo_db
    volumes:
      - todo_pg_data:/var/lib/postgresql/data
    ports:
      - "54320:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo -d todo_db || exit 1"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 3s

  api:
    build:
      context: ..
      dockerfile: app/backend/Dockerfile
    environment:
      DATABASE_URL: postgresql://todo:todo@db:5432/todo_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  todo_pg_data:
