version: "3.9"

networks:
  todo_net: {}

volumes:
  todo_pg_data: {}

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB:   ${POSTGRES_DB}
      POSTGRES_PASSWORD_FILE: /run/secrets/todo_pg_password
    secrets:
      - todo_pg_password
    volumes:
      - todo_pg_data:/var/lib/postgresql/data
    networks:
      - todo_net
    deploy:
      placement:
        constraints:
          - node.role == manager

  api:
    image: swarm-todo-api:1.0.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB:   ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PASSWORD_FILE: /run/secrets/todo_pg_password   # ← اضافه کن
    secrets:
      - todo_pg_password
    ports:
      - "8080:8000"
    networks:
      - todo_net
    depends_on:
      - db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager



secrets:
  todo_pg_password:
    external: true